<?php

// Archive photos and posters supplied by GODRAM. Captions describe only
// what is visible; they can be corrected here without touching code.
return [
    ['file' => 'godram-10.webp', 'title' => 'Majemu (Covenant)', 'caption' => 'Victory Drama Crusade poster, Bolorunpelu, Egbe, 22 to 24 July 1994', 'year' => 1994, 'kind' => 'poster'],
    ['file' => 'godram-31.webp', 'title' => 'GICD Intensive Training', 'caption' => 'Ordinary and Advanced Certificate in Christian Drama, Odo Eran, Matori, 1999', 'year' => 1999, 'kind' => 'poster'],
    ['file' => 'godram-11.webp', 'title' => 'GODRAM family', 'caption' => 'Members gathered after a ministration', 'year' => null, 'kind' => 'photo'],
    ['file' => 'godram-21.webp', 'title' => 'GONACIC 2009', 'caption' => 'National Cinematography Induction Course', 'year' => 2009, 'kind' => 'poster'],
    ['file' => 'godram-12.webp', 'title' => 'Drama ministers', 'caption' => 'A GODRAM gathering from the archive', 'year' => null, 'kind' => 'photo'],
    ['file' => 'godram-1.webp', 'title' => 'The Handwriting', 'caption' => 'Film poster from the GODRAM archive', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-25.webp', 'title' => 'Pioneering Graduation', 'caption' => 'GICD graduation programme, Ayantuga Street, Mushin', 'year' => 1995, 'kind' => 'document'],
    ['file' => 'godram-13.webp', 'title' => 'Presentation', 'caption' => 'An award presentation from the archive', 'year' => null, 'kind' => 'photo'],
    ['file' => 'godram-29.webp', 'title' => 'There is a Season', 'caption' => 'GACASA poster', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-34.webp', 'title' => 'Change', 'caption' => 'Production artwork', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-20.webp', 'title' => 'Majemu Aye', 'caption' => 'Worldly Covenant production brochure', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-2.webp', 'title' => 'Fellowship', 'caption' => 'Members and children at a GODRAM programme', 'year' => null, 'kind' => 'photo'],
    ['file' => 'godram-35.webp', 'title' => "Progressional News '98", 'caption' => 'GODRAM newsletter, 1998', 'year' => 1998, 'kind' => 'document'],
    ['file' => 'godram-22.webp', 'title' => 'GODRAM Films', 'caption' => 'Films available for sponsorship', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-28.webp', 'title' => 'GODRAM of GOFAMINT', 'caption' => 'Poster artwork', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-8.webp', 'title' => 'Retreat 2006', 'caption' => 'Ministers retreat poster', 'year' => 2006, 'kind' => 'poster'],
    ['file' => 'godram-14.webp', 'title' => 'At the venue', 'caption' => 'Members gathered outside a programme venue', 'year' => null, 'kind' => 'photo'],
    ['file' => 'godram-15.webp', 'title' => 'GODRAM Institute of Christian Drama', 'caption' => 'GICD admission poster: a training ground for drama ministers', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-17.webp', 'title' => 'Majemu Aye', 'caption' => 'A GODRAM Films production, written and directed by Paul P. Edemonsi', 'year' => 1994, 'kind' => 'poster'],
    ['file' => 'godram-16.webp', 'title' => 'Majemu Aye cast', 'caption' => 'Cast and crew pages of the Majemu Aye brochure', 'year' => 1994, 'kind' => 'document'],
    ['file' => 'godram-23.webp', 'title' => 'Special Invitation', 'caption' => 'GODRAM of GOFAMINT invitation card', 'year' => null, 'kind' => 'poster'],
    ['file' => 'godram-18.webp', 'title' => 'Pioneering Graduation invitation', 'caption' => 'GICD graduation ceremony invitation, 18 March 1995, with The Macedonian Call', 'year' => 1995, 'kind' => 'document'],
    ['file' => 'godram-19.webp', 'title' => 'The Macedonian Call', 'caption' => 'Appeal card listing the equipment GICD needed', 'year' => 1995, 'kind' => 'document'],
    ['file' => 'godram-9.webp', 'title' => 'GICD Brochure', 'caption' => 'GODRAM Institute of Christian Drama brochure', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-24.webp', 'title' => 'The Macedonian Call letter', 'caption' => 'Letter appealing for support for the Institute', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-30.webp', 'title' => 'Aims and objectives', 'caption' => 'Illustrated page from a GODRAM publication', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-32.webp', 'title' => 'Illustrated page', 'caption' => 'Artwork from a GODRAM publication', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-27.webp', 'title' => 'Membership application', 'caption' => 'GODRAM membership application form', 'year' => null, 'kind' => 'document'],
    ['file' => 'godram-26.webp', 'title' => "Pastor's recommendation", 'caption' => 'Recommendation letter form for applicants', 'year' => null, 'kind' => 'document'],
];
