<?php

// Performance and ministry photographs supplied by GODRAM, kept in
// public/images/gallery. Captions describe only what the folder names and
// the pictures themselves show; correct them here without touching code.
$convention = fn ($n, $what) => ['file' => "convention-2026-$n.webp", 'title' => 'Beyond the Room', 'caption' => "Convention 2026 drama ministration: $what", 'year' => 2026];
$outreach = fn ($n, $what) => ['file' => "outreach-$n.webp", 'title' => 'Drama outreach', 'caption' => $what, 'year' => null];
$osun = fn ($n, $what) => ['file' => "osun-conference-$n.webp", 'title' => 'Osun State Conference', 'caption' => $what, 'year' => null];
$stage = fn ($n, $what) => ['file' => "stage-drama-$n.webp", 'title' => 'Stage drama', 'caption' => $what, 'year' => null];

return [
    $convention('5878', 'the market scene'),
    $convention('5832', 'a scene before the floral curtain'),
    $convention('5923', 'the cast on stage'),
    $convention('5887', 'a scene in the village set'),
    $convention('5944', 'the cast together on stage'),
    $convention('5899', 'the market women'),
    $convention('5911', 'a scene on the bench'),
    $convention('5929', 'the cast in song'),
    $convention('5807', 'flags of the nations'),
    $convention('5938', 'the full cast before the congregation'),
    $convention('5947', 'the cast at the close'),
    $convention('5884', 'a scene in the village set'),
    $convention('5905', 'a scene before the congregation'),
    $convention('5914', 'a family scene'),
    $convention('5826', 'a scene on the red stage'),
    $convention('5857', 'a scene before the floral curtain'),
    $convention('5866', 'the waiting scene'),
    $outreach('4731', 'Worship during an outreach'),
    $outreach('4786', 'The crowd at a night outreach'),
    $outreach('4802', 'Worship at a night outreach'),
    $outreach('4819', 'The congregation at an outreach'),
    $outreach('4817', 'Gathered for a night outreach'),
    $osun('5706', 'Delegates in the hall'),
    $osun('5700', 'Young delegates listening'),
    $osun('5716', 'Delegates during a session'),
    $osun('5726', 'A delegate during a session'),
    $osun('5683', 'Young delegates during a session'),
    $osun('5709', 'Delegates during a session'),
    $stage('4415', 'A ministration on stage'),
    $stage('05131', 'Ministers on stage'),
    $stage('05102', 'The cast on stage'),
    // Added October 2026: more of the Convention 2026 ministration and the other folders.
    $convention('5805', 'flags of the nations'),
    $convention('5817', 'a scene on the red stage'),
    $convention('5822', 'two men in a tense exchange'),
    $convention('5831', 'a scene under the draped cloth'),
    $convention('5851', 'a confrontation'),
    $convention('5871', 'the crowd scene'),
    $convention('5877', 'the market women at work'),
    $convention('5892', 'the market scene'),
    $convention('5910', 'a scene on the bench'),
    $convention('5932', 'the cast in song'),
    $convention('5796', 'make-up before the ministration'),
    $convention('5800', 'flags of the nations'),
    $convention('5814', 'a scene on the red stage'),
    $convention('5818', 'a scene on the red stage'),
    $convention('5824', 'two men in a tense exchange'),
    $convention('5827', 'a family scene'),
    $convention('5829', 'a family scene'),
    $convention('5836', 'a scene under the draped cloth'),
    $convention('5839', 'a scene under the draped cloth'),
    $convention('5842', 'a scene under the draped cloth'),
    $convention('5847', 'a scene under the draped cloth'),
    $convention('5853', 'a scene before the floral curtain'),
    $convention('5855', 'a scene before the floral curtain'),
    $convention('5860', 'the waiting scene'),
    $convention('5862', 'the waiting scene'),
    $convention('5867', 'the crowd scene'),
    $convention('5873', 'the market scene'),
    $convention('5875', 'the market women'),
    $convention('5880', 'the market women'),
    $convention('5881', 'the market scene'),
    $convention('5885', 'the market women'),
    $convention('5888', 'a scene in the village set'),
    $convention('5890', 'a scene in the village set'),
    $convention('5893', 'the market women'),
    $convention('5898', 'the market women'),
    $convention('5901', 'the market women'),
    $convention('5902', 'a scene before the congregation'),
    $convention('5906', 'a scene before the congregation'),
    $convention('5908', 'a scene in the village set'),
    $convention('5913', 'a scene on the bench'),
    $convention('5916', 'a scene on the bench'),
    $convention('5920', 'the cast in song'),
    $convention('5922', 'the cast in song'),
    $convention('5925', 'the cast before the congregation'),
    $convention('5926', 'the cast in song'),
    $convention('5927', 'the cast in song'),
    $convention('5933', 'the cast in song'),
    $convention('5935', 'the cast in song'),
    $convention('5940', 'the cast together on stage'),
    $convention('5942', 'the cast together on stage'),
    $convention('5946', 'the full cast before the congregation'),
    $outreach('4758', 'Ministering to the crowd at a night outreach'),
    $outreach('4760', 'Families at a night outreach'),
    $outreach('4785', 'Praise at a night outreach'),
    $outreach('4803', 'Worship at a night outreach'),
    $outreach('4807', 'Children and families at an outreach'),
    $outreach('4818', 'Responding at an outreach'),
    $outreach('4824', 'The crowd at a night outreach'),
    $osun('5676', 'Delegates during a session'),
    $osun('5678', 'Delegates during a session'),
    $osun('5680', 'Delegates in the hall'),
    $osun('5690', 'A speaker during a session'),
    $osun('5712', 'Delegates taking notes'),
    $osun('5719', 'Delegates during a session'),
    $osun('5722', 'A delegate during a session'),
    $osun('5730', 'A speaker during a session'),
    $stage('05111', 'The cast on stage'),
    $stage('05115', 'A minister on stage'),
    $stage('05119', 'A minister on stage'),
    $stage('05126', 'Ministers on stage'),
    $stage('05143', 'A minister on stage'),
    $stage('05158', 'The cast on stage'),
    $stage('05163', 'A minister on stage'),
    $stage('05166', 'Ministers on stage'),
    $stage('05167', 'Worship on stage'),
    $stage('05170', 'A minister on stage'),
    $stage('4406', 'A ministration on stage'),
    $stage('4417', 'A moment of reconciliation on stage'),
];
